<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Traits\FileHandler;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
class CountrySeeder extends Seeder
{
    use FileHandler;
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries_list = array(
            array("name" => "Afghanistan", "code" => "AF", "phone_extension" => "93", "french" => "Afghanistan", "spanish" => "Afganistán", "arabic" => "أفغانستان"),
            array("name" => "Aland Islands", "code" => "AX", "phone_extension" => "358", "french" => "Îles Åland", "spanish" => "Islas Åland", "arabic" => "جزر آلاند"),
            array("name" => "Albania", "code" => "AL", "phone_extension" => "355", "french" => "Albanie", "spanish" => "Albania", "arabic" => "ألبانيا"),
            array("name" => "Algeria", "code" => "DZ", "phone_extension" => "213", "french" => "Algérie", "spanish" => "Argelia", "arabic" => "الجزائر"),
            array("name" => "American Samoa", "code" => "AS", "phone_extension" => "1684", "french" => "Samoa américaines", "spanish" => "Samoa Americana", "arabic" => "ساموا الأمريكية"),
            array("name" => "Andorra", "code" => "AD", "phone_extension" => "376", "french" => "Andorre", "spanish" => "Andorra", "arabic" => "أندورا"),
            array("name" => "Angola", "code" => "AO", "phone_extension" => "244", "french" => "Angola", "spanish" => "Angola", "arabic" => "أنغولا"),
            array("name" => "Anguilla", "code" => "AI", "phone_extension" => "1264", "french" => "Anguilla", "spanish" => "Anguila", "arabic" => "أنغويلا"),
            array("name" => "Antarctica", "code" => "AQ", "phone_extension" => "672", "french" => "Antarctique", "spanish" => "Antártida", "arabic" => "القطب الجنوبي"),
            array("name" => "Antigua and Barbuda", "code" => "AG", "phone_extension" => "1268", "french" => "Antigua-et-Barbuda", "spanish" => "Antigua y Barbuda", "arabic" => "أنتيغوا وبربودا"),
            array("name" => "Argentina", "code" => "AR", "phone_extension" => "54", "french" => "Argentine", "spanish" => "Argentina", "arabic" => "الأرجنتين"),
            array("name" => "Armenia", "code" => "AM", "phone_extension" => "374", "french" => "Arménie", "spanish" => "Armenia", "arabic" => "أرمينيا"),
            array("name" => "Aruba", "code" => "AW", "phone_extension" => "297", "french" => "Aruba", "spanish" => "Aruba", "arabic" => "أروبا"),
            array("name" => "Australia", "code" => "AU", "phone_extension" => "61", "french" => "Australie", "spanish" => "Australia", "arabic" => "أستراليا"),
            array("name" => "Austria", "code" => "AT", "phone_extension" => "43", "french" => "Autriche", "spanish" => "Austria", "arabic" => "النمسا"),
            array("name" => "Azerbaijan", "code" => "AZ", "phone_extension" => "994", "french" => "Azerbaïdjan", "spanish" => "Azerbaiyán", "arabic" => "أذربيجان"),
            array("name" => "Bahamas", "code" => "BS", "phone_extension" => "1242", "french" => "Bahamas", "spanish" => "Bahamas", "arabic" => "الباهاما"),
            array("name" => "Bahrain", "code" => "BH", "phone_extension" => "973", "french" => "Bahreïn", "spanish" => "Baréin", "arabic" => "البحرين"),
            array("name" => "Bangladesh", "code" => "BD", "phone_extension" => "880", "french" => "Bangladesh", "spanish" => "Bangladés", "arabic" => "بنغلاديش"),
            array("name" => "Barbados", "code" => "BB", "phone_extension" => "1246", "french" => "Barbade", "spanish" => "Barbados", "arabic" => "بربادوس"),
            array("name" => "Belarus", "code" => "BY", "phone_extension" => "375", "french" => "Biélorussie", "spanish" => "Bielorrusia", "arabic" => "بيلاروس"),
            array("name" => "Belgium", "code" => "BE", "phone_extension" => "32", "french" => "Belgique", "spanish" => "Bélgica", "arabic" => "بلجيكا"),
            array("name" => "Belize", "code" => "BZ", "phone_extension" => "501", "french" => "Belize", "spanish" => "Belice", "arabic" => "بليز"),
            array("name" => "Benin", "code" => "BJ", "phone_extension" => "229", "french" => "Bénin", "spanish" => "Benín", "arabic" => "بنين"),
            array("name" => "Bermuda", "code" => "BM", "phone_extension" => "1441", "french" => "Bermudes", "spanish" => "Bermudas", "arabic" => "برمودا"),
            array("name" => "Bhutan", "code" => "BT", "phone_extension" => "975", "french" => "Bhoutan", "spanish" => "Bután", "arabic" => "بوتان"),
            array("name" => "Bolivia", "code" => "BO", "phone_extension" => "591", "french" => "Bolivie", "spanish" => "Bolivia", "arabic" => "بوليفيا"),
            array("name" => "Bosnia and Herzegovina", "code" => "BA", "phone_extension" => "387", "french" => "Bosnie-Herzégovine", "spanish" => "Bosnia y Herzegovina", "arabic" => "البوسنة والهرسك"),
            array("name" => "Botswana", "code" => "BW", "phone_extension" => "267", "french" => "Botswana", "spanish" => "Botsuana", "arabic" => "بوتسوانا"),
            array("name" => "Bouvet Island", "code" => "BV", "phone_extension" => "47", "french" => "Île Bouvet", "spanish" => "Isla Bouvet", "arabic" => "جزيرة بوفيه"),
            array("name" => "Brazil", "code" => "BR", "phone_extension" => "55", "french" => "Brésil", "spanish" => "Brasil", "arabic" => "البرازيل"),
            array("name" => "British Indian Ocean Territory", "code" => "IO", "phone_extension" => "246", "french" => "Territoire britannique de l'océan Indien", "spanish" => "Territorio Británico del Océano Índico", "arabic" => "إقليم المحيط الهندي البريطاني"),
            array("name" => "Brunei Darussalam", "code" => "BN", "phone_extension" => "673", "french" => "Brunéi Darussalam", "spanish" => "Brunéi", "arabic" => "بروناي دار السلام"),

            array("name" => "Bulgaria", "code" => "BG", "phone_extension" => "359", "french" => "Bulgarie", "spanish" => "Bulgaria", "arabic" => "بلغاريا"),
            array("name" => "Burkina Faso", "code" => "BF", "phone_extension" => "226", "french" => "Burkina Faso", "spanish" => "Burkina Faso", "arabic" => "بوركينا فاسو"),
            array("name" => "Burundi", "code" => "BI", "phone_extension" => "257", "french" => "Burundi", "spanish" => "Burundi", "arabic" => "بوروندي"),
            array("name" => "Cambodia", "code" => "KH", "phone_extension" => "855", "french" => "Cambodge", "spanish" => "Camboya", "arabic" => "كمبوديا"),
            array("name" => "Cameroon", "code" => "CM", "phone_extension" => "237", "french" => "Cameroun", "spanish" => "Camerún", "arabic" => "الكاميرون"),
            array("name" => "Canada", "code" => "CA", "phone_extension" => "1", "french" => "Canada", "spanish" => "Canadá", "arabic" => "كندا"),
            array("name" => "Cape Verde", "code" => "CV", "phone_extension" => "238", "french" => "Cap-Vert", "spanish" => "Cabo Verde", "arabic" => "الرأس الأخضر"),
            array("name" => "Cayman Islands", "code" => "KY", "phone_extension" => "1345", "french" => "Îles Caïmans", "spanish" => "Islas Caimán", "arabic" => "جزر الكايمان"),
            array("name" => "Central African Republic", "code" => "CF", "phone_extension" => "236", "french" => "République centrafricaine", "spanish" => "República Centroafricana", "arabic" => "جمهورية أفريقيا الوسطى"),
            array("name" => "Chad", "code" => "TD", "phone_extension" => "235", "french" => "Tchad", "spanish" => "Chad", "arabic" => "تشاد"),
            array("name" => "Chile", "code" => "CL", "phone_extension" => "56", "french" => "Chili", "spanish" => "Chile", "arabic" => "تشيلي"),
            array("name" => "China", "code" => "CN", "phone_extension" => "86", "french" => "Chine", "spanish" => "China", "arabic" => "الصين"),
            array("name" => "Christmas Island", "code" => "CX", "phone_extension" => "61", "french" => "Île Christmas", "spanish" => "Isla de Navidad", "arabic" => "جزيرة الكريسماس"),
            array("name" => "Cocos (Keeling) Islands", "code" => "CC", "phone_extension" => "61", "french" => "Îles Cocos (Keeling)", "spanish" => "Islas Cocos", "arabic" => "جزر كوكوس (كيلينغ)"),
            array("name" => "Colombia", "code" => "CO", "phone_extension" => "57", "french" => "Colombie", "spanish" => "Colombia", "arabic" => "كولومبيا"),
            array("name" => "Comoros", "code" => "KM", "phone_extension" => "269", "french" => "Comores", "spanish" => "Comoras", "arabic" => "جزر القمر"),
            array("name" => "Cote D'Ivoire", "code" => "CI", "phone_extension" => "225", "french" => "Côte d'Ivoire", "spanish" => "Costa de Marfil", "arabic" => "ساحل العاج"),
            array("name" => "Croatia", "code" => "HR", "phone_extension" => "385", "french" => "Croatie", "spanish" => "Croacia", "arabic" => "كرواتيا"),
            array("name" => "Cuba", "code" => "CU", "phone_extension" => "53", "french" => "Cuba", "spanish" => "Cuba", "arabic" => "كوبا"),
            array("name" => "Curacao", "code" => "CW", "phone_extension" => "599", "french" => "Curaçao", "spanish" => "Curazao", "arabic" => "كوراساو"),
            array("name" => "Cyprus", "code" => "CY", "phone_extension" => "357", "french" => "Chypre", "spanish" => "Chipre", "arabic" => "قبرص"),
            array("name" => "Czech Republic", "code" => "CZ", "phone_extension" => "420", "french" => "République tchèque", "spanish" => "República Checa", "arabic" => "جمهورية التشيك"),
            array("name" => "Denmark", "code" => "DK", "phone_extension" => "45", "french" => "Danemark", "spanish" => "Dinamarca", "arabic" => "الدنمارك"),
            array("name" => "Djibouti", "code" => "DJ", "phone_extension" => "253", "french" => "Djibouti", "spanish" => "Yibuti", "arabic" => "جيبوتي"),
            array("name" => "Dominica", "code" => "DM", "phone_extension" => "1767", "french" => "Dominique", "spanish" => "Dominica", "arabic" => "دومينيكا"),
            array("name" => "Dominican Republic", "code" => "DO", "phone_extension" => "1809", "french" => "République dominicaine", "spanish" => "República Dominicana", "arabic" => "جمهورية الدومينيكان"),
            array("name" => "Ecuador", "code" => "EC", "phone_extension" => "593", "french" => "Équateur", "spanish" => "Ecuador", "arabic" => "الإكوادور"),
            array("name" => "Egypt", "code" => "EG", "phone_extension" => "20", "french" => "Égypte", "spanish" => "Egipto", "arabic" => "مصر"),
            array("name" => "El Salvador", "code" => "SV", "phone_extension" => "503", "french" => "Salvador", "spanish" => "El Salvador", "arabic" => "السلفادور"),
            array("name" => "Equatorial Guinea", "code" => "GQ", "phone_extension" => "240", "french" => "Guinée équatoriale", "spanish" => "Guinea Ecuatorial", "arabic" => "غينيا الاستوائية"),
            array("name" => "Eritrea", "code" => "ER", "phone_extension" => "291", "french" => "Érythrée", "spanish" => "Eritrea", "arabic" => "إريتريا"),
            array("name" => "Estonia", "code" => "EE", "phone_extension" => "372", "french" => "Estonie", "spanish" => "Estonia", "arabic" => "إستونيا"),
            array("name" => "Ethiopia", "code" => "ET", "phone_extension" => "251", "french" => "Éthiopie", "spanish" => "Etiopía", "arabic" => "إثيوبيا"),
            array("name" => "Falkland Islands (Malvinas)", "code" => "FK", "phone_extension" => "500", "french" => "Îles Falkland (Malvinas)", "spanish" => "Islas Malvinas", "arabic" => "جزر فوكلاند (مالفيناس)"),
            array("name" => "Faroe Islands", "code" => "FO", "phone_extension" => "298", "french" => "Îles Féroé", "spanish" => "Islas Feroe", "arabic" => "جزر فارو"),
            array("name" => "Fiji", "code" => "FJ", "phone_extension" => "679", "french" => "Fidji", "spanish" => "Fiyi", "arabic" => "فيجي"),
            array("name" => "Finland", "code" => "FI", "phone_extension" => "358", "french" => "Finlande", "spanish" => "Finlandia", "arabic" => "فنلندا"),
            array("name" => "France", "code" => "FR", "phone_extension" => "33", "french" => "France", "spanish" => "Francia", "arabic" => "فرنسا"),
            array("name" => "French Guiana", "code" => "GF", "phone_extension" => "594", "french" => "Guyane française", "spanish" => "Guayana Francesa", "arabic" => "غويانا الفرنسية"),
            array("name" => "French Polynesia", "code" => "PF", "phone_extension" => "689", "french" => "Polynésie française", "spanish" => "Polinesia Francesa", "arabic" => "بولينيزيا الفرنسية"),
            array("name" => "French Southern Territories", "code" => "TF", "phone_extension" => "262", "french" => "Terres australes françaises", "spanish" => "Territorios Franceses del Sur", "arabic" => "المقاطعات الفرنسية الجنوبية"),

            array("name" => "Gabon", "code" => "GA", "phone_extension" => "241", "french" => "Gabon", "spanish" => "Gabón", "arabic" => "الغابون"),
            array("name" => "Gambia", "code" => "GM", "phone_extension" => "220", "french" => "Gambie", "spanish" => "Gambia", "arabic" => "غامبيا"),
            array("name" => "Georgia", "code" => "GE", "phone_extension" => "995", "french" => "Géorgie", "spanish" => "Georgia", "arabic" => "جورجيا"),
            array("name" => "Germany", "code" => "DE", "phone_extension" => "49", "french" => "Allemagne", "spanish" => "Alemania", "arabic" => "ألمانيا"),
            array("name" => "Ghana", "code" => "GH", "phone_extension" => "233", "french" => "Ghana", "spanish" => "Ghana", "arabic" => "غانا"),
            array("name" => "Gibraltar", "code" => "GI", "phone_extension" => "350", "french" => "Gibraltar", "spanish" => "Gibraltar", "arabic" => "جبل طارق"),
            array("name" => "Greece", "code" => "GR", "phone_extension" => "30", "french" => "Grèce", "spanish" => "Grecia", "arabic" => "اليونان"),
            array("name" => "Greenland", "code" => "GL", "phone_extension" => "299", "french" => "Groenland", "spanish" => "Groenlandia", "arabic" => "غرينلاند"),
            array("name" => "Grenada", "code" => "GD", "phone_extension" => "1473", "french" => "Grenade", "spanish" => "Granada", "arabic" => "غرينادا"),
            array("name" => "Guadeloupe", "code" => "GP", "phone_extension" => "590", "french" => "Guadeloupe", "spanish" => "Guadalupe", "arabic" => "غوادلوب"),
            array("name" => "Guam", "code" => "GU", "phone_extension" => "1671", "french" => "Guam", "spanish" => "Guam", "arabic" => "غوام"),
            array("name" => "Guatemala", "code" => "GT", "phone_extension" => "502", "french" => "Guatemala", "spanish" => "Guatemala", "arabic" => "غواتيمالا"),
            array("name" => "Guernsey", "code" => "GG", "phone_extension" => "44", "french" => "Guernesey", "spanish" => "Guernsey", "arabic" => "جيرنزي"),
            array("name" => "Guinea", "code" => "GN", "phone_extension" => "224", "french" => "Guinée", "spanish" => "Guinea", "arabic" => "غينيا"),
            array("name" => "Guinea-Bissau", "code" => "GW", "phone_extension" => "245", "french" => "Guinée-Bissau", "spanish" => "Guinea-Bissau", "arabic" => "غينيا بيساو"),
            array("name" => "Guyana", "code" => "GY", "phone_extension" => "592", "french" => "Guyana", "spanish" => "Guyana", "arabic" => "غيانا"),

            array("name" => "Haiti", "code" => "HT", "phone_extension" => "509", "french" => "Haïti", "spanish" => "Haití", "arabic" => "هايتي"),
            array("name" => "Heard Island and Mcdonald Islands", "code" => "HM", "phone_extension" => "0", "french" => "Île Heard et îles McDonald", "spanish" => "Isla Heard e Islas McDonald", "arabic" => "جزيرة هيرد وجزر ماكدونالد"),
            array("name" => "Holy See (Vatican City State)", "code" => "VA", "phone_extension" => "39", "french" => "Saint-Siège (État de la Cité du Vatican)", "spanish" => "Santa Sede (Ciudad del Vaticano)", "arabic" => "الكرسي الرسولي (مدينة الفاتيكان)"),
            array("name" => "Honduras", "code" => "HN", "phone_extension" => "504", "french" => "Honduras", "spanish" => "Honduras", "arabic" => "هندوراس"),
            array("name" => "Hong Kong", "code" => "HK", "phone_extension" => "852", "french" => "Hong Kong", "spanish" => "Hong Kong", "arabic" => "هونغ كونغ"),
            array("name" => "Hungary", "code" => "HU", "phone_extension" => "36", "french" => "Hongrie", "spanish" => "Hungría", "arabic" => "هنغاريا"),
            array("name" => "Iceland", "code" => "IS", "phone_extension" => "354", "french" => "Islande", "spanish" => "Islandia", "arabic" => "آيسلندا"),
            array("name" => "India", "code" => "IN", "phone_extension" => "91", "french" => "Inde", "spanish" => "India", "arabic" => "الهند"),
            array("name" => "Indonesia", "code" => "ID", "phone_extension" => "62", "french" => "Indonésie", "spanish" => "Indonesia", "arabic" => "إندونيسيا"),
            array("name" => "Iran, Islamic Republic of", "code" => "IR", "phone_extension" => "98", "french" => "Iran, République islamique d'", "spanish" => "Irán, República Islámica de", "arabic" => "إيران، الجمهورية الإسلامية الإيرانية"),
            array("name" => "Iraq", "code" => "IQ", "phone_extension" => "964", "french" => "Irak", "spanish" => "Irak", "arabic" => "العراق"),
            array("name" => "Ireland", "code" => "IE", "phone_extension" => "353", "french" => "Irlande", "spanish" => "Irlanda", "arabic" => "أيرلندا"),
            array("name" => "Isle of Man", "code" => "IM", "phone_extension" => "44", "french" => "Île de Man", "spanish" => "Isla de Man", "arabic" => "جزيرة مان"),
            array("name" => "Italy", "code" => "IT", "phone_extension" => "39", "french" => "Italie", "spanish" => "Italia", "arabic" => "إيطاليا"),
            array("name" => "Jamaica", "code" => "JM", "phone_extension" => "1876", "french" => "Jamaïque", "spanish" => "Jamaica", "arabic" => "جامايكا"),
            array("name" => "Japan", "code" => "JP", "phone_extension" => "81", "french" => "Japon", "spanish" => "Japón", "arabic" => "اليابان"),
            array("name" => "Jersey", "code" => "JE", "phone_extension" => "44", "french" => "Jersey", "spanish" => "Jersey", "arabic" => "جيرسي"),
            array("name" => "Jordan", "code" => "JO", "phone_extension" => "962", "french" => "Jordanie", "spanish" => "Jordania", "arabic" => "الأردن"),
            array("name" => "Kazakhstan", "code" => "KZ", "phone_extension" => "7", "french" => "Kazakhstan", "spanish" => "Kazajistán", "arabic" => "كازاخستان"),
            array("name" => "Kenya", "code" => "KE", "phone_extension" => "254", "french" => "Kenya", "spanish" => "Kenia", "arabic" => "كينيا"),
            array("name" => "Kiribati", "code" => "KI", "phone_extension" => "686", "french" => "Kiribati", "spanish" => "Kiribati", "arabic" => "كيريباتي"),
            array("name" => "Korea, Democratic People's Republic of", "code" => "KP", "phone_extension" => "850", "french" => "Corée du Nord", "spanish" => "Corea del Norte", "arabic" => "كوريا الشمالية"),
            array("name" => "Korea, Republic of", "code" => "KR", "phone_extension" => "82", "french" => "Corée du Sud", "spanish" => "Corea del Sur", "arabic" => "كوريا الجنوبية"),
            array("name" => "Kosovo", "code" => "XK", "phone_extension" => "381", "french" => "Kosovo", "spanish" => "Kosovo", "arabic" => "كوسوفو"),
            array("name" => "Kuwait", "code" => "KW", "phone_extension" => "965", "french" => "Koweït", "spanish" => "Kuwait", "arabic" => "الكويت"),
            array("name" => "Kyrgyzstan", "code" => "KG", "phone_extension" => "996", "french" => "Kirghizistan", "spanish" => "Kirguistán", "arabic" => "قيرغيزستان"),
            array("name" => "Lao People's Democratic Republic", "code" => "LA", "phone_extension" => "856", "french" => "République démocratique populaire lao", "spanish" => "República Democrática Popular Lao", "arabic" => "جمهورية لاو الديمقراطية الشعبية"),
            array("name" => "Latvia", "code" => "LV", "phone_extension" => "371", "french" => "Lettonie", "spanish" => "Letonia", "arabic" => "لاتفيا"),
            array("name" => "Lebanon", "code" => "LB", "phone_extension" => "961", "french" => "Liban", "spanish" => "Líbano", "arabic" => "لبنان"),
            array("name" => "Lesotho", "code" => "LS", "phone_extension" => "266", "french" => "Lesotho", "spanish" => "Lesoto", "arabic" => "ليسوتو"),
            array("name" => "Liberia", "code" => "LR", "phone_extension" => "231", "french" => "Libéria", "spanish" => "Liberia", "arabic" => "ليبيريا"),
            array("name" => "Libyan Arab Jamahiriya", "code" => "LY", "phone_extension" => "218", "french" => "Libye", "spanish" => "Libia", "arabic" => "الجماهيرية العربية الليبية"),
            array("name" => "Liechtenstein", "code" => "LI", "phone_extension" => "423", "french" => "Liechtenstein", "spanish" => "Liechtenstein", "arabic" => "ليختنشتاين"),
            array("name" => "Lithuania", "code" => "LT", "phone_extension" => "370", "french" => "Lituanie", "spanish" => "Lituania", "arabic" => "ليتوانيا"),
            array("name" => "Luxembourg", "code" => "LU", "phone_extension" => "352", "french" => "Luxembourg", "spanish" => "Luxemburgo", "arabic" => "لوكسمبورغ"),

            array("name" => "Macao", "code" => "MO", "phone_extension" => "853", "french" => "Macao", "spanish" => "Macao", "arabic" => "ماكاو"),
            array("name" => "Macedonia, the Former Yugoslav Republic of", "code" => "MK", "phone_extension" => "389", "french" => "Macédoine, ex-République yougoslave de", "spanish" => "Macedonia, Antigua República Yugoslava de", "arabic" => "مقدونيا، جمهورية يوغوسلافيا السابقة"),
            array("name" => "Madagascar", "code" => "MG", "phone_extension" => "261", "french" => "Madagascar", "spanish" => "Madagascar", "arabic" => "مدغشقر"),
            array("name" => "Malawi", "code" => "MW", "phone_extension" => "265", "french" => "Malawi", "spanish" => "Malaui", "arabic" => "ملاوي"),
            array("name" => "Malaysia", "code" => "MY", "phone_extension" => "60", "french" => "Malaisie", "spanish" => "Malasia", "arabic" => "ماليزيا"),
            array("name" => "Maldives", "code" => "MV", "phone_extension" => "960", "french" => "Maldives", "spanish" => "Maldivas", "arabic" => "جزر الملديف"),
            array("name" => "Mali", "code" => "ML", "phone_extension" => "223", "french" => "Mali", "spanish" => "Malí", "arabic" => "مالي"),
            array("name" => "Malta", "code" => "MT", "phone_extension" => "356", "french" => "Malte", "spanish" => "Malta", "arabic" => "مالطا"),
            array("name" => "Marshall Islands", "code" => "MH", "phone_extension" => "692", "french" => "Îles Marshall", "spanish" => "Islas Marshall", "arabic" => "جزر مارشال"),
            array("name" => "Martinique", "code" => "MQ", "phone_extension" => "596", "french" => "Martinique", "spanish" => "Martinica", "arabic" => "مارتينيك"),
            array("name" => "Mauritania", "code" => "MR", "phone_extension" => "222", "french" => "Mauritanie", "spanish" => "Mauritania", "arabic" => "موريتانيا"),
            array("name" => "Mauritius", "code" => "MU", "phone_extension" => "230", "french" => "Maurice", "spanish" => "Mauricio", "arabic" => "موريشيوس"),
            array("name" => "Mayotte", "code" => "YT", "phone_extension" => "262", "french" => "Mayotte", "spanish" => "Mayotte", "arabic" => "مايوت"),
            array("name" => "Mexico", "code" => "MX", "phone_extension" => "52", "french" => "Mexique", "spanish" => "México", "arabic" => "المكسيك"),
            array("name" => "Micronesia, Federated States of", "code" => "FM", "phone_extension" => "691", "french" => "Micronésie, États fédérés de", "spanish" => "Micronesia, Estados Federados de", "arabic" => "ميكرونيزيا، ولايات ميكرونيزيا المتحدة"),
            array("name" => "Moldova, Republic of", "code" => "MD", "phone_extension" => "373", "french" => "Moldavie, République de", "spanish" => "Moldova, República de", "arabic" => "مولدوفا، جمهورية"),
            array("name" => "Monaco", "code" => "MC", "phone_extension" => "377", "french" => "Monaco", "spanish" => "Mónaco", "arabic" => "موناكو"),
            array("name" => "Mongolia", "code" => "MN", "phone_extension" => "976", "french" => "Mongolie", "spanish" => "Mongolia", "arabic" => "منغوليا"),
            array("name" => "Montenegro", "code" => "ME", "phone_extension" => "382", "french" => "Monténégro", "spanish" => "Montenegro", "arabic" => "الجبل الأسود"),
            array("name" => "Montserrat", "code" => "MS", "phone_extension" => "1664", "french" => "Montserrat", "spanish" => "Montserrat", "arabic" => "مونتسيرات"),
            array("name" => "Morocco", "code" => "MA", "phone_extension" => "212", "french" => "Maroc", "spanish" => "Marruecos", "arabic" => "المغرب"),
            array("name" => "Mozambique", "code" => "MZ", "phone_extension" => "258", "french" => "Mozambique", "spanish" => "Mozambique", "arabic" => "موزمبيق"),
            array("name" => "Myanmar", "code" => "MM", "phone_extension" => "95", "french" => "Myanmar", "spanish" => "Myanmar", "arabic" => "ميانمار"),
            array("name" => "Namibia", "code" => "NA", "phone_extension" => "264", "french" => "Namibie", "spanish" => "Namibia", "arabic" => "ناميبيا"),
            array("name" => "Nauru", "code" => "NR", "phone_extension" => "674", "french" => "Nauru", "spanish" => "Nauru", "arabic" => "ناورو"),
            array("name" => "Nepal", "code" => "NP", "phone_extension" => "977", "french" => "Népal", "spanish" => "Nepal", "arabic" => "نيبال"),
            array("name" => "Netherlands", "code" => "NL", "phone_extension" => "31", "french" => "Pays-Bas", "spanish" => "Países Bajos", "arabic" => "هولندا"),
            array("name" => "Netherlands Antilles", "code" => "AN", "phone_extension" => "599", "french" => "Antilles néerlandaises", "spanish" => "Antillas Neerlandesas", "arabic" => "جزر الأنتيل الهولندية"),
            array("name" => "New Caledonia", "code" => "NC", "phone_extension" => "687", "french" => "Nouvelle-Calédonie", "spanish" => "Nueva Caledonia", "arabic" => "كاليدونيا الجديدة"),
            array("name" => "New Zealand", "code" => "NZ", "phone_extension" => "64", "french" => "Nouvelle-Zélande", "spanish" => "Nueva Zelanda", "arabic" => "نيوزيلندا"),
            array("name" => "Nicaragua", "code" => "NI", "phone_extension" => "505", "french" => "Nicaragua", "spanish" => "Nicaragua", "arabic" => "نيكاراغوا"),
            array("name" => "Niger", "code" => "NE", "phone_extension" => "227", "french" => "Niger", "spanish" => "Níger", "arabic" => "النيجر"),
            array("name" => "Nigeria", "code" => "NG", "phone_extension" => "234", "french" => "Nigeria", "spanish" => "Nigeria", "arabic" => "نيجيريا"),
            array("name" => "Niue", "code" => "NU", "phone_extension" => "683", "french" => "Niue", "spanish" => "Niue", "arabic" => "نيوي"),
            array("name" => "Norfolk Island", "code" => "NF", "phone_extension" => "672", "french" => "Île Norfolk", "spanish" => "Isla Norfolk", "arabic" => "جزيرة نورفولك"),
            array("name" => "Northern Mariana Islands", "code" => "MP", "phone_extension" => "1670", "french" => "Îles Mariannes du Nord", "spanish" => "Islas Marianas del Norte", "arabic" => "جزر ماريانا الشمالية"),
            array("name" => "Norway", "code" => "NO", "phone_extension" => "47", "french" => "Norvège", "spanish" => "Noruega", "arabic" => "النرويج"),
            array("name" => "Oman", "code" => "OM", "phone_extension" => "968", "french" => "Oman", "spanish" => "Omán", "arabic" => "عمان"),
            array("name" => "Pakistan", "code" => "PK", "phone_extension" => "92", "french" => "Pakistan", "spanish" => "Pakistán", "arabic" => "باكستان"),
            array("name" => "Palau", "code" => "PW", "phone_extension" => "680", "french" => "Palaos", "spanish" => "Palaos", "arabic" => "بالاو"),
            array("name" => "Palestinian Territory, Occupied", "code" => "PS", "phone_extension" => "970", "french" => "Territoire palestinien occupé", "spanish" => "Territorio Palestino Ocupado", "arabic" => "الأراضي الفلسطينية المحتلة"),
            array("name" => "Panama", "code" => "PA", "phone_extension" => "507", "french" => "Panama", "spanish" => "Panamá", "arabic" => "بنما"),
            array("name" => "Papua New Guinea", "code" => "PG", "phone_extension" => "675", "french" => "Papouasie-Nouvelle-Guinée", "spanish" => "Papúa Nueva Guinea", "arabic" => "بابوا غينيا الجديدة"),
            array("name" => "Paraguay", "code" => "PY", "phone_extension" => "595", "french" => "Paraguay", "spanish" => "Paraguay", "arabic" => "باراغواي"),
            array("name" => "Peru", "code" => "PE", "phone_extension" => "51", "french" => "Pérou", "spanish" => "Perú", "arabic" => "بيرو"),
            array("name" => "Philippines", "code" => "PH", "phone_extension" => "63", "french" => "Philippines", "spanish" => "Filipinas", "arabic" => "الفلبين"),
            array("name" => "Pitcairn", "code" => "PN", "phone_extension" => "64", "french" => "Îles Pitcairn", "spanish" => "Islas Pitcairn", "arabic" => "بيتكايرن"),
            array("name" => "Poland", "code" => "PL", "phone_extension" => "48", "french" => "Pologne", "spanish" => "Polonia", "arabic" => "بولندا"),
            array("name" => "Portugal", "code" => "PT", "phone_extension" => "351", "french" => "Portugal", "spanish" => "Portugal", "arabic" => "البرتغال"),
            array("name" => "Puerto Rico", "code" => "PR", "phone_extension" => "1787", "french" => "Porto Rico", "spanish" => "Puerto Rico", "arabic" => "بورتوريكو"),
            array("name" => "Qatar", "code" => "QA", "phone_extension" => "974", "french" => "Qatar", "spanish" => "Catar", "arabic" => "قطر"),
            array("name" => "Reunion", "code" => "RE", "phone_extension" => "262", "french" => "Réunion", "spanish" => "Reunión", "arabic" => "روينيون"),
            array("name" => "Romania", "code" => "RO", "phone_extension" => "40", "french" => "Roumanie", "spanish" => "Rumania", "arabic" => "رومانيا"),
            array("name" => "Russian Federation", "code" => "RU", "phone_extension" => "70", "french" => "Fédération de Russie", "spanish" => "Federación de Rusia", "arabic" => "روسيا الاتحادية"),
            array("name" => "Rwanda", "code" => "RW", "phone_extension" => "250", "french" => "Rwanda", "spanish" => "Ruanda", "arabic" => "رواندا"),
            array("name" => "Saint Barthelemy", "code" => "BL", "phone_extension" => "590", "french" => "Saint-Barthélemy", "spanish" => "San Bartolomé", "arabic" => "سانت بارتيلمي"),
            array("name" => "Saint Helena", "code" => "SH", "phone_extension" => "290", "french" => "Sainte-Hélène", "spanish" => "Santa Elena", "arabic" => "سانت هيلينا"),
            array("name" => "Saint Kitts and Nevis", "code" => "KN", "phone_extension" => "1869", "french" => "Saint-Kitts-et-Nevis", "spanish" => "San Cristóbal y Nieves", "arabic" => "سانت كيتس ونيفيس"),
            array("name" => "Saint Lucia", "code" => "LC", "phone_extension" => "1758", "french" => "Sainte-Lucie", "spanish" => "Santa Lucía", "arabic" => "سانت لوسيا"),
            array("name" => "Saint Martin", "code" => "MF", "phone_extension" => "590", "french" => "Saint-Martin", "spanish" => "San Martín", "arabic" => "سانت مارتن"),
            array("name" => "Saint Pierre and Miquelon", "code" => "PM", "phone_extension" => "508", "french" => "Saint-Pierre-et-Miquelon", "spanish" => "San Pedro y Miquelón", "arabic" => "سانت بيير وميكلون"),
            array("name" => "Saint Vincent and the Grenadines", "code" => "VC", "phone_extension" => "1784", "french" => "Saint-Vincent-et-les Grenadines", "spanish" => "San Vicente y las Granadinas", "arabic" => "سانت فينسنت والغرينادينز"),
            array("name" => "Samoa", "code" => "WS", "phone_extension" => "684", "french" => "Samoa", "spanish" => "Samoa", "arabic" => "ساموا"),
            array("name" => "San Marino", "code" => "SM", "phone_extension" => "378", "french" => "Saint-Marin", "spanish" => "San Marino", "arabic" => "سان مارينو"),
            array("name" => "Sao Tome and Principe", "code" => "ST", "phone_extension" => "239", "french" => "Sao Tomé-et-Principe", "spanish" => "Santo Tomé y Príncipe", "arabic" => "ساو تومي وبرينسيبي"),
            array("name" => "Saudi Arabia", "code" => "SA", "phone_extension" => "966", "french" => "Arabie saoudite", "spanish" => "Arabia Saudita", "arabic" => "المملكة العربية السعودية"),
            array("name" => "Senegal", "code" => "SN", "phone_extension" => "221", "french" => "Sénégal", "spanish" => "Senegal", "arabic" => "السنغال"),
            array("name" => "Serbia", "code" => "RS", "phone_extension" => "381", "french" => "Serbie", "spanish" => "Serbia", "arabic" => "صربيا"),
            array("name" => "Serbia and Montenegro", "code" => "CS", "phone_extension" => "381", "french" => "Serbie-et-Monténégro", "spanish" => "Serbia y Montenegro", "arabic" => "صربيا والجبل الأسود"),
            array("name" => "Seychelles", "code" => "SC", "phone_extension" => "248", "french" => "Seychelles", "spanish" => "Seychelles", "arabic" => "سيشل"),
            array("name" => "Sierra Leone", "code" => "SL", "phone_extension" => "232", "french" => "Sierra Leone", "spanish" => "Sierra Leona", "arabic" => "سيراليون"),
            array("name" => "Singapore", "code" => "SG", "phone_extension" => "65", "french" => "Singapour", "spanish" => "Singapur", "arabic" => "سنغافورة"),
            array("name" => "Sint Maarten", "code" => "SX", "phone_extension" => "1", "french" => "Sint Maarten", "spanish" => "Sint Maarten", "arabic" => "سينت مارتن"),
            array("name" => "Slovakia", "code" => "SK", "phone_extension" => "421", "french" => "Slovaquie", "spanish" => "Eslovaquia", "arabic" => "سلوفاكيا"),
            array("name" => "Slovenia", "code" => "SI", "phone_extension" => "386", "french" => "Slovénie", "spanish" => "Eslovenia", "arabic" => "سلوفينيا"),
            array("name" => "Solomon Islands", "code" => "SB", "phone_extension" => "677", "french" => "Îles Salomon", "spanish" => "Islas Salomón", "arabic" => "جزر سليمان"),
            array("name" => "Somalia", "code" => "SO", "phone_extension" => "252", "french" => "Somalie", "spanish" => "Somalia", "arabic" => "الصومال"),
            array("name" => "South Africa", "code" => "ZA", "phone_extension" => "27", "french" => "Afrique du Sud", "spanish" => "Sudáfrica", "arabic" => "جنوب أفريقيا"),
            array("name" => "South Georgia and the South Sandwich Islands", "code" => "GS", "phone_extension" => "500", "french" => "Géorgie du Sud-et-les Îles Sandwich du Sud", "spanish" => "Islas Georgias del Sur y Sandwich del Sur", "arabic" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية"),
            array("name" => "South Sudan", "code" => "SS", "phone_extension" => "211", "french" => "Soudan du Sud", "spanish" => "Sudán del Sur", "arabic" => "جنوب السودان"),
            array("name" => "Spain", "code" => "ES", "phone_extension" => "34", "french" => "Espagne", "spanish" => "España", "arabic" => "إسبانيا"),
            array("name" => "Sri Lanka", "code" => "LK", "phone_extension" => "94", "french" => "Sri Lanka", "spanish" => "Sri Lanka", "arabic" => "سريلانكا"),
            array("name" => "Sudan", "code" => "SD", "phone_extension" => "249", "french" => "Soudan", "spanish" => "Sudán", "arabic" => "السودان"),
            array("name" => "Suriname", "code" => "SR", "phone_extension" => "597", "french" => "Suriname", "spanish" => "Surinam", "arabic" => "سورينام"),
            array("name" => "Svalbard and Jan Mayen", "code" => "SJ", "phone_extension" => "47", "french" => "Svalbard et Jan Mayen", "spanish" => "Svalbard y Jan Mayen", "arabic" => "سفالبارد وجان ماين"),
            array("name" => "Swaziland", "code" => "SZ", "phone_extension" => "268", "french" => "Swaziland", "spanish" => "Esuatini", "arabic" => "سوازيلاند"),
            array("name" => "Sweden", "code" => "SE", "phone_extension" => "46", "french" => "Suède", "spanish" => "Suecia", "arabic" => "السويد"),
            array("name" => "Switzerland", "code" => "CH", "phone_extension" => "41", "french" => "Suisse", "spanish" => "Suiza", "arabic" => "سويسرا"),
            array("name" => "Syrian Arab Republic", "code" => "SY", "phone_extension" => "963", "french" => "République arabe syrienne", "spanish" => "República Árabe Siria", "arabic" => "الجمهورية العربية السورية"),
            array("name" => "Taiwan, Province of China", "code" => "TW", "phone_extension" => "886", "french" => "Taïwan", "spanish" => "Taiwán", "arabic" => "تايوان، مقاطعة الصين"),
            array("name" => "Tajikistan", "code" => "TJ", "phone_extension" => "992", "french" => "Tadjikistan", "spanish" => "Tayikistán", "arabic" => "طاجيكستان"),
            array("name" => "Tanzania, United Republic of", "code" => "TZ", "phone_extension" => "255", "french" => "Tanzanie", "spanish" => "Tanzania", "arabic" => "تنزانيا، جمهورية متحدة"),
            array("name" => "Thailand", "code" => "TH", "phone_extension" => "66", "french" => "Thaïlande", "spanish" => "Tailandia", "arabic" => "تايلاند"),
            array("name" => "Timor-Leste", "code" => "TL", "phone_extension" => "670", "french" => "Timor-Leste", "spanish" => "Timor Oriental", "arabic" => "تيمور الشرقية"),
            array("name" => "Togo", "code" => "TG", "phone_extension" => "228", "french" => "Togo", "spanish" => "Togo", "arabic" => "توغو"),
            array("name" => "Tokelau", "code" => "TK", "phone_extension" => "690", "french" => "Tokelau", "spanish" => "Tokelau", "arabic" => "توكيلاو"),
            array("name" => "Tonga", "code" => "TO", "phone_extension" => "676", "french" => "Tonga", "spanish" => "Tonga", "arabic" => "تونجا"),
            array("name" => "Trinidad and Tobago", "code" => "TT", "phone_extension" => "1868", "french" => "Trinité-et-Tobago", "spanish" => "Trinidad y Tobago", "arabic" => "ترينيداد وتوباغو"),
            array("name" => "Tunisia", "code" => "TN", "phone_extension" => "216", "french" => "Tunisie", "spanish" => "Túnez", "arabic" => "تونس"),
            array("name" => "Turkey", "code" => "TR", "phone_extension" => "90", "french" => "Turquie", "spanish" => "Turquía", "arabic" => "تركيا"),
            array("name" => "Turkmenistan", "code" => "TM", "phone_extension" => "7370", "french" => "Turkménistan", "spanish" => "Turkmenistán", "arabic" => "تركمانستان"),
            array("name" => "Turks and Caicos Islands", "code" => "TC", "phone_extension" => "1649", "french" => "Îles Turques-et-Caïques", "spanish" => "Islas Turcas y Caicos", "arabic" => "جزر تركس وكايكوس"),
            array("name" => "Tuvalu", "code" => "TV", "phone_extension" => "688", "french" => "Tuvalu", "spanish" => "Tuvalu", "arabic" => "توفالو"),

            array("name" => "Uganda", "code" => "UG", "phone_extension" => "256", "french" => "Ouganda", "spanish" => "Uganda", "arabic" => "أوغندا"),
            array("name" => "Ukraine", "code" => "UA", "phone_extension" => "380", "french" => "Ukraine", "spanish" => "Ucrania", "arabic" => "أوكرانيا"),
            array("name" => "United Arab Emirates", "code" => "AE", "phone_extension" => "971", "french" => "Émirats arabes unis", "spanish" => "Emiratos Árabes Unidos", "arabic" => "الإمارات العربية المتحدة"),
            array("name" => "United Kingdom", "code" => "GB", "phone_extension" => "44", "french" => "Royaume-Uni", "spanish" => "Reino Unido", "arabic" => "المملكة المتحدة"),
            array("name" => "United States", "code" => "US", "phone_extension" => "1", "french" => "États-Unis", "spanish" => "Estados Unidos", "arabic" => "الولايات المتحدة الأمريكية"),
            array("name" => "United States Minor Outlying Islands", "code" => "UM", "phone_extension" => "1", "french" => "Îles mineures éloignées des États-Unis", "spanish" => "Islas menores alejadas de los Estados Unidos", "arabic" => "جزر الولايات المتحدة البعيدة الصغيرة"),
            array("name" => "Uruguay", "code" => "UY", "phone_extension" => "598", "french" => "Uruguay", "spanish" => "Uruguay", "arabic" => "أوروغواي"),
            array("name" => "Uzbekistan", "code" => "UZ", "phone_extension" => "998", "french" => "Ouzbékistan", "spanish" => "Uzbekistán", "arabic" => "أوزبكستان"),
            array("name" => "Vanuatu", "code" => "VU", "phone_extension" => "678", "french" => "Vanuatu", "spanish" => "Vanuatu", "arabic" => "فانواتو"),
            array("name" => "Venezuela", "code" => "VE", "phone_extension" => "58", "french" => "Venezuela", "spanish" => "Venezuela", "arabic" => "فنزويلا"),
            array("name" => "Viet Nam", "code" => "VN", "phone_extension" => "84", "french" => "Viêt Nam", "spanish" => "Vietnam", "arabic" => "فيتنام"),
            array("name" => "Virgin Islands, British", "code" => "VG", "phone_extension" => "1284", "french" => "Îles Vierges britanniques", "spanish" => "Islas Vírgenes Británicas", "arabic" => "جزر العذراء البريطانية"),
            array("name" => "Virgin Islands, U.s.", "code" => "VI", "phone_extension" => "1340", "french" => "Îles Vierges des États-Unis", "spanish" => "Islas Vírgenes de los Estados Unidos", "arabic" => "جزر العذراء الأمريكية"),
            array("name" => "Wallis and Futuna", "code" => "WF", "phone_extension" => "681", "french" => "Wallis-et-Futuna", "spanish" => "Wallis y Futuna", "arabic" => "والس وفوتونا"),
            array("name" => "Western Sahara", "code" => "EH", "phone_extension" => "212", "french" => "Sahara occidental", "spanish" => "Sahara Occidental", "arabic" => "الصحراء الغربية"),
            array("name" => "Yemen", "code" => "YE", "phone_extension" => "967", "french" => "Yémen", "spanish" => "Yemen", "arabic" => "اليمن"),
            array("name" => "Zambia", "code" => "ZM", "phone_extension" => "260", "french" => "Zambie", "spanish" => "Zambia", "arabic" => "زامبيا"),
            array("name" => "Zimbabwe", "code" => "ZW", "phone_extension" => "263", "french" => "Zimbabwe", "spanish" => "Zimbabue", "arabic" => "زيمبابوي"),

        );

        foreach ($countries_list as $country) {
            $code = isset($country['code']) ? strtoupper($country['code']) : '';
            $codeSlug = strtolower($code);
            $path = 'images/flags/1x1/' . $codeSlug . '.svg';
            $localPath = public_path($path);
            $extension = pathinfo($path, PATHINFO_EXTENSION);
            $flagPath = null;
            if (file_exists($localPath)) {
                $image_content = file_get_contents($localPath);
                $flagPath = $this->storeImage($image_content, 'flags', $extension);
            }
            $newCountry = Country::updateOrCreate([
                'phone_extension' => "+" . $country['phone_extension'],
                'code' => $code,
            ], [
                'phone_extension' => "+" . $country['phone_extension'],
                'code' => $code,
                'flag' => $flagPath,
            ]);
            $translations = [
                'en' => $country['name'],
                'ar' => $country['arabic'],
            ];
            foreach ($translations as $locale => $translation) {
                $newCountry->translateOrNew($locale)->name = $translation;
            }
            $newCountry->save();
        }
    }
}
